---
##################################################
# PHASE 2: Configure Lustre with LDISKFS
#
# This phase:
# - Verifies the Lustre kernel is running
# - Installs Lustre LDISKFS OSD
# - Creates Lustre MGS/MDT/OST on loop devices
# - Sets up test scenarios for project quota behavior
# - Generates the descriptive test script
# - Configures systemd for boot persistence
##################################################
- name: Configure Lustre Environment with LDISKFS
  hosts: all
  become: true
  vars:
    lustre_fsname: "testfs"
    lustre_mgsnode: "192.168.60.10@tcp0"

  tasks:
    # --------------------------------------------------
    # Kernel Verification
    # --------------------------------------------------
    - name: Verify Lustre kernel is running
      command: uname -r
      register: kernel_version
      failed_when: "'lustre' not in kernel_version.stdout"
      changed_when: false

    # --------------------------------------------------
    # LDISKFS Installation
    # --------------------------------------------------
    - name: Install Lustre LDISKFS OSD and utilities
      dnf:
        name: [kmod-lustre-osd-ldiskfs, lustre-osd-ldiskfs-mount, e2fsprogs, strace, bc]
        state: present

    # --------------------------------------------------
    # Lustre Module Loading
    # --------------------------------------------------
    - name: Load Lustre modules
      shell: |
        modprobe -v lnet
        modprobe -v lustre
        modprobe -v osd_ldiskfs
      register: modprobe_result
      changed_when: false

    # --------------------------------------------------
    # LNet Configuration
    # --------------------------------------------------
    - name: Detect network interface for private network
      shell: ip -o addr show | grep '192.168.60.10' | awk '{print $2}'
      register: private_interface
      changed_when: false

    - name: Configure LNet
      shell: |
        lnetctl lnet configure 2>/dev/null || true
        lnetctl net add --net tcp0 --if {{ private_interface.stdout }} 2>/dev/null || true
      changed_when: false

    # --------------------------------------------------
    # Create Backing Devices (Loop Devices)
    # --------------------------------------------------
    - name: Create backing files
      command: truncate -s {{ item.size }} {{ item.path }}
      args:
        creates: "{{ item.path }}"
      loop:
        - { path: "/var/lib/lustre-mdt.img", size: "2G" }
        - { path: "/var/lib/lustre-ost.img", size: "10G" }

    - name: Setup loop devices
      shell: |
        if ! losetup -j /var/lib/lustre-mdt.img | grep -q loop; then losetup -f /var/lib/lustre-mdt.img; fi
        if ! losetup -j /var/lib/lustre-ost.img | grep -q loop; then losetup -f /var/lib/lustre-ost.img; fi
      changed_when: false

    - name: Get loop device paths
      shell: |
        MDT=$(losetup -j /var/lib/lustre-mdt.img | cut -d: -f1)
        OST=$(losetup -j /var/lib/lustre-ost.img | cut -d: -f1)
        echo "$MDT,$OST"
      register: loop_paths
      changed_when: false

    - name: Set loop facts
      set_fact:
        mdt_dev: "{{ loop_paths.stdout.split(',')[0] }}"
        ost_dev: "{{ loop_paths.stdout.split(',')[1] }}"

    # --------------------------------------------------
    # Format & Mount Lustre (Fixed Idempotency)
    # --------------------------------------------------
    - name: Check if Lustre is already live
      command: mountpoint -q /mnt/lustre
      register: lustre_live
      failed_when: false
      changed_when: false

    - name: Check if MDT device has a filesystem
      shell: "tunefs.lustre {{ mdt_dev }} | grep -q 'Target:.*MDT'"
      register: mdt_formatted
      failed_when: false
      changed_when: false
      when: lustre_live.rc != 0

    - name: Format MGS/MDT
      command: >
        mkfs.lustre --reformat --fsname={{ lustre_fsname }} --mgs --mdt
        --backfstype=ldiskfs --index=0 --mkfsoptions="-O project,quota" {{ mdt_dev }}
      when: 
        - lustre_live.rc != 0
        - mdt_formatted.rc is defined and mdt_formatted.rc != 0

    - name: Check if OST device has a filesystem
      shell: "tunefs.lustre {{ ost_dev }} | grep -q 'Target:.*OST'"
      register: ost_formatted
      failed_when: false
      changed_when: false
      when: lustre_live.rc != 0

    - name: Format OST
      command: >
        mkfs.lustre --reformat --fsname={{ lustre_fsname }} --ost
        --backfstype=ldiskfs --index=0 --mgsnode={{ lustre_mgsnode }}
        --mkfsoptions="-O project,quota" {{ ost_dev }}
      when: 
        - lustre_live.rc != 0
        - ost_formatted.rc is defined and ost_formatted.rc != 0

    - name: Create mount points
      file:
        path: "{{ item }}"
        state: directory
      loop: [/mnt/mdt, /mnt/ost, /mnt/lustre]

    - name: Mount Targets
      shell: |
        mountpoint -q /mnt/mdt || mount -t lustre {{ mdt_dev }} /mnt/mdt
        mountpoint -q /mnt/ost || mount -t lustre {{ ost_dev }} /mnt/ost
        sleep 2
        mountpoint -q /mnt/lustre || mount -t lustre {{ lustre_mgsnode }}:/{{ lustre_fsname }} /mnt/lustre
      changed_when: false

    # --------------------------------------------------
    # Quota & Directory Setup
    # --------------------------------------------------
    - name: Enable project quota
      shell: |
        lctl conf_param {{ lustre_fsname }}.quota.mdt=ugp
        lctl conf_param {{ lustre_fsname }}.quota.ost=ugp
      changed_when: false

    - name: Create scenario directories
      file:
        path: "/mnt/lustre/{{ item }}"
        state: directory
      loop: [scenario1_proj100, scenario1_proj200, scenario2_proj300_src, scenario2_proj300_dst]

    - name: Assign Project IDs
      shell: |
        lfs project -s -p 100 -r /mnt/lustre/scenario1_proj100
        lfs project -s -p 200 -r /mnt/lustre/scenario1_proj200
        lfs project -s -p 300 -r /mnt/lustre/scenario2_proj300_src
        lfs project -s -p 300 -r /mnt/lustre/scenario2_proj300_dst
      changed_when: false

    # --------------------------------------------------
    # Test Script Generation (Improved Logging)
    # --------------------------------------------------
    - name: Create comprehensive test script
      copy:
        dest: /root/run_tests.sh
        mode: '0755'
        content: |
          #!/bin/bash
          set -euo pipefail

          BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
          
          print_header() { 
              echo -e "\n${BLUE}================================================================${NC}"
              echo -e "${BLUE}$1${NC}"
              echo -e "${BLUE}================================================================${NC}"
          }
          
          print_cmd() { echo -e "${YELLOW}Executing:${NC} $1"; }
          
          print_test_result() {
              echo -e "\n${GREEN}TEST RESULT:${NC}"
              echo -e "  Operation: $1"
              echo -e "  Timing:    $2s"
              echo -e "  Outcome:   $3"
          }

          cd /mnt/lustre
          print_header "LUSTRE PROJECT QUOTA - ISOLATED TEST SUITE"
          echo "Kernel: $(uname -r) | Lustre: $(lctl version 2>/dev/null | head -1 || echo 'N/A')"

          # --------------------------------------------------
          # TEST 0: Baseline File Move
          # --------------------------------------------------
          print_header "TEST 0: File Move Across Projects (Baseline)"
          dd if=/dev/urandom of=scenario1_proj100/testfile.bin bs=1M count=50 status=none
          
          T_START=$(date +%s.%N)
          print_cmd "mv scenario1_proj100/testfile.bin scenario1_proj200/testfile.bin"
          strace -e renameat,renameat2 mv scenario1_proj100/testfile.bin scenario1_proj200/testfile.bin 2>&1 | grep -E "renameat|EXDEV" || true
          T_END=$(date +%s.%N)
          
          T_FILE_BASE=$(echo "$T_END - $T_START" | bc)
          NEW_ID=$(lfs project scenario1_proj200/testfile.bin | awk '{print $1}')
          
          print_test_result "Atomic File Rename" "$T_FILE_BASE" "SUCCESS (New ID: $NEW_ID)"
          rm -f scenario1_proj200/testfile.bin

          # --------------------------------------------------
          # TEST 1: Directory EXDEV Detection
          # --------------------------------------------------
          print_header "TEST 1: EXDEV Detection (Directory Move)"
          mkdir -p scenario1_proj100/testdir
          lfs project -s -p 100 -r scenario1_proj100/testdir >/dev/null
          
          echo -e "${YELLOW}Running strace on directory move...${NC}"
          STRACE_OUT=$(strace -e renameat,renameat2 mv scenario1_proj100/testdir scenario1_proj200/testdir 2>&1 || true)
          echo "$STRACE_OUT" | grep -E "renameat|EXDEV" || true
          
          if echo "$STRACE_OUT" | grep -q "EXDEV"; then
              OUTCOME="${RED}EXDEV DETECTED (Copy+Delete Required)${NC}"
          else
              OUTCOME="Rename Succeeded"
          fi
          print_test_result "Cross-Project Directory Move" "N/A" "$OUTCOME"
          rm -rf scenario1_proj200/testdir scenario1_proj100/testdir

          # --------------------------------------------------
          # TEST 2: Slow Path Timing
          # --------------------------------------------------
          print_header "TEST 2: Slow Path Timing (500MB Cross-Project)"
          mkdir -p scenario1_proj100/slowdir
          dd if=/dev/urandom of=scenario1_proj100/slowdir/big.bin bs=1M count=500 status=none
          lfs project -s -p 100 -r scenario1_proj100/slowdir >/dev/null
          
          T1=$(date +%s.%N)
          print_cmd "mv scenario1_proj100/slowdir scenario1_proj200/slowdir"
          mv scenario1_proj100/slowdir scenario1_proj200/slowdir
          T2=$(date +%s.%N)
          
          TSLOW=$(echo "$T2 - $T1" | bc)
          print_test_result "Recursive Copy + Delete" "$TSLOW" "FORCED BY EXDEV"
          rm -rf scenario1_proj200/slowdir

          # --------------------------------------------------
          # TEST 3: Fast Path Timing
          # --------------------------------------------------
          print_header "TEST 3: Fast Path Timing (500MB Same-Project)"
          mkdir -p scenario2_proj300_src/fastdir
          dd if=/dev/urandom of=scenario2_proj300_src/fastdir/big.bin bs=1M count=500 status=none
          lfs project -s -p 300 -r scenario2_proj300_src/fastdir >/dev/null
          
          T3=$(date +%s.%N)
          print_cmd "mv scenario2_proj300_src/fastdir scenario2_proj300_dst/fastdir"
          mv scenario2_proj300_src/fastdir scenario2_proj300_dst/fastdir
          T4=$(date +%s.%N)
          
          TFAST=$(echo "$T4 - $T3" | bc)
          print_test_result "Atomic Metadata Rename" "$TFAST" "SUCCESS"
          rm -rf scenario2_proj300_dst/fastdir

          # --------------------------------------------------
          # TEST 4: Workaround Timing
          # --------------------------------------------------
          print_header "TEST 4: Workaround Timing (ID Alignment)"
          mkdir -p scenario1_proj100/workaround
          lfs project -s -p 100 -r scenario1_proj100/workaround >/dev/null
          
          print_cmd "lfs project -s -p 200 -r scenario1_proj100/workaround"
          lfs project -s -p 200 -r scenario1_proj100/workaround >/dev/null
          
          T5=$(date +%s.%N)
          print_cmd "mv scenario1_proj100/workaround scenario1_proj200/workaround"
          mv scenario1_proj100/workaround scenario1_proj200/workaround
          T6=$(date +%s.%N)
          
          TWORK=$(echo "$T6 - $T5" | bc)
          print_test_result "Aligned Project ID Move" "$TWORK" "SUCCESS (Atomic)"
          rm -rf scenario1_proj200/workaround

          # --------------------------------------------------
          # FINAL SUMMARY
          # --------------------------------------------------
          print_header "FINAL COMPARATIVE SUMMARY"
          echo -e "  File Baseline (Atomic):    ${T_FILE_BASE}s"
          echo -e "  Directory Slow Path (EXDEV): ${TSLOW}s"
          echo -e "  Directory Fast Path (Same):  ${TFAST}s"
          echo -e "  Directory Workaround:        ${TWORK}s"
          
          DIFF=$(echo "scale=2; $TSLOW / $TFAST" | bc 2>/dev/null || echo "N/A")
          echo -e "\n${BLUE}Conclusion:${NC} Cross-project moves are ${DIFF}x slower than atomic renames."
          print_header "ALL TESTS COMPLETE"
    # --------------------------------------------------
    # Persistence Configuration
    # --------------------------------------------------
    - name: Create systemd service for persistence
      copy:
        dest: /etc/systemd/system/lustre-test.service
        mode: '0644'
        content: |
          [Unit]
          Description=Mount Lustre Test Filesystem
          After=network.target
          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/bin/bash -c 'MDT=$(losetup -j /var/lib/lustre-mdt.img | cut -d: -f1); OST=$(losetup -j /var/lib/lustre-ost.img | cut -d: -f1); lnetctl lnet configure 2>/dev/null || true; IFACE=$(ip -o addr show | grep 192.168.60.10 | awk "{print \$2}"); lnetctl net add --net tcp0 --if $IFACE 2>/dev/null || true; mountpoint -q /mnt/mdt || mount -t lustre $MDT /mnt/mdt; mountpoint -q /mnt/ost || mount -t lustre $OST /mnt/ost; sleep 2; mountpoint -q /mnt/lustre || mount -t lustre 192.168.60.10@tcp0:/testfs /mnt/lustre'
          [Install]
          WantedBy=multi-user.target

    - name: Enable Lustre test service
      systemd: { name: lustre-test, enabled: yes, daemon_reload: yes }

    - name: Final Success Message
      debug: { msg: "Phase 2 Complete. Run 'sudo /root/run_tests.sh' inside the VM." }
